import "dotenv/config";
import { PrismaClient } from "@prisma/client";
import { PrismaPg } from "@prisma/adapter-pg";
import { randomBytes, scryptSync } from "node:crypto";

const prisma = new PrismaClient({ adapter: new PrismaPg({ connectionString: process.env.DATABASE_URL }) });

function hashPassword(password: string): string {
  const salt = randomBytes(16).toString("hex");
  const derived = scryptSync(password, salt, 64).toString("hex");
  return `${salt}:${derived}`;
}

interface SeedProduct {
  name: string;
  description: string;
  category: string;
  price: number;
  salePrice: number | null;
  isOnSale: boolean;
  saleLabel: string | null;
  stock: number;
  featured: boolean;
  imageUrl: string;
  isWholesale?: boolean;
  wholesaleUnitName?: string;
  wholesaleUnitQuantity?: number;
}

const img = (id: string) => `https://images.unsplash.com/${id}?w=600&q=80`;

const PRODUCTS: SeedProduct[] = [
  // ─── Ropa de hombre y mujer ───────────────────────────────────────────────
  {
    name: "Blazer Estructurado Milano",
    description: "Blazer de corte estructurado en lana fría, hombros definidos y cierre de botón único. Pieza clave para un look de oficina impecable.",
    category: "Chaquetas",
    price: 189.0,
    salePrice: 139.0,
    isOnSale: true,
    saleLabel: "Oferta de temporada",
    stock: 24,
    featured: true,
    imageUrl: img("photo-1594633312681-425c7b97ccd1"),
  },
  {
    name: "Camisa Oxford Blanco",
    description: "Camisa clásica en algodón oxford de tejido italiano. Cuello semisoft y costura de doble aguja para un acabado resistente.",
    category: "Camisetas",
    price: 59.0,
    salePrice: null,
    isOnSale: false,
    saleLabel: null,
    stock: 60,
    featured: true,
    imageUrl: img("photo-1602810318383-e386cc2a3ccf"),
  },
  {
    name: "Vestido Midi Seda Bordeaux",
    description: "Vestido midi en seda natural con caída fluida, escote en pico y cintura drapeada. Perfecto para eventos de noche.",
    category: "Vestidos",
    price: 220.0,
    salePrice: 165.0,
    isOnSale: true,
    saleLabel: "Últimas unidades",
    stock: 12,
    featured: false,
    imageUrl: img("photo-1610030469983-98e550d6193c"),
  },
  {
    name: "Sneakers Urban Canvas",
    description: "Sneakers de lona premium con suela de goma vulcanizada. Silueta limpia que combina con todo.",
    category: "Zapatos",
    price: 89.0,
    salePrice: null,
    isOnSale: false,
    saleLabel: null,
    stock: 45,
    featured: false,
    imageUrl: img("photo-1542291026-7eec264c27ff"),
  },
  {
    name: "Hoodie Heavyweight Gris",
    description: "Sudadera de algodón pesado 450gsm con capucha doble forrada y bolsillo canguro. Talle oversize.",
    category: "Sudaderas",
    price: 75.0,
    salePrice: 52.0,
    isOnSale: true,
    saleLabel: "Flash sale",
    stock: 30,
    featured: false,
    imageUrl: img("photo-1556821840-3a63f95609a7"),
  },
  {
    name: "Pantalón Chino Slim",
    description: "Chino en sarga de algodón con corte slim y cintura ajustada con stretch. Versátil de oficina a fin de semana.",
    category: "Pantalones",
    price: 69.0,
    salePrice: null,
    isOnSale: false,
    saleLabel: null,
    stock: 50,
    featured: false,
    imageUrl: img("photo-1473966968600-fa801b869a1a"),
  },
  {
    name: "Trench Coat Camel",
    description: "Gabinete clásico en gabardina color camel con forro a cuadros, cinturón y botones de madera. Atemporal.",
    category: "Abrigos",
    price: 259.0,
    salePrice: 194.0,
    isOnSale: true,
    saleLabel: "Pieza de colección",
    stock: 8,
    featured: true,
    imageUrl: img("photo-1544022613-e87ca75a784a"),
  },
  {
    name: "Bolso Tote Piel Negra",
    description: "Tote de piel genuina con interior forrado, compartimento para laptop y asas reforzadas.",
    category: "Accesorios",
    price: 149.0,
    salePrice: null,
    isOnSale: false,
    saleLabel: null,
    stock: 18,
    featured: false,
    imageUrl: img("photo-1584917865442-de89df76afd3"),
  },
  {
    name: "Camiseta Básica Premium Hombre",
    description: "Camiseta de algodón peinado 220gsm, cuello reforzado y corte regular. Básico esencial en colores neutros.",
    category: "Camisetas",
    price: 25.0,
    salePrice: null,
    isOnSale: false,
    saleLabel: null,
    stock: 80,
    featured: false,
    imageUrl: img("photo-1521572163474-6864f9cf17ab"),
  },
  {
    name: "Chaqueta de Cuero Cropped Mujer",
    description: "Chaqueta corta de piel sintética premium con cremallera asimétrica y cuello moto. Detalle rockero para el día a día.",
    category: "Chaquetas",
    price: 135.0,
    salePrice: 108.0,
    isOnSale: true,
    saleLabel: "Outlet",
    stock: 14,
    featured: false,
    imageUrl: img("photo-1520975954732-35dd22299614"),
  },
  {
    name: "Blusa Seda Estampada Mujer",
    description: "Blusa fluida en seda con estampado floral, cuello bandeau y mangas amplias. Elegante y ligera.",
    category: "Camisetas",
    price: 85.0,
    salePrice: null,
    isOnSale: false,
    saleLabel: null,
    stock: 22,
    featured: false,
    imageUrl: img("photo-1515886657613-9f3515b0c78f"),
  },
  {
    name: "Jeans Skinny Mujer",
    description: "Jeans de mezclilla con elastano, talle alto y corte skinny. Comodidad con ajuste favorecedor.",
    category: "Pantalones",
    price: 55.0,
    salePrice: 39.0,
    isOnSale: true,
    saleLabel: "Liquidación",
    stock: 40,
    featured: false,
    imageUrl: img("photo-1542272604-787c3835535d"),
  },
  {
    name: "Vestido Casual de Verano",
    description: "Vestido ligero de algodón con hombros descubiertos y largo midi. Frescura para el día.",
    category: "Vestidos",
    price: 68.0,
    salePrice: null,
    isOnSale: false,
    saleLabel: null,
    stock: 25,
    featured: false,
    imageUrl: img("photo-1496747611176-843222e1e57c"),
  },
  {
    name: "Saco de Punto Hombre",
    description: "Saco de punto de lana merino con botones frontales y bolsillos. Calidez sofisticada.",
    category: "Chaquetas",
    price: 98.0,
    salePrice: null,
    isOnSale: false,
    saleLabel: null,
    stock: 16,
    featured: false,
    imageUrl: img("photo-1516826957135-700dedea698c"),
  },
  {
    name: "Camisa Casual a Cuadros Hombre",
    description: "Camisa de franela a cuadros con corte regular y botones de presión. Look casual de fin de semana.",
    category: "Camisetas",
    price: 42.0,
    salePrice: null,
    isOnSale: false,
    saleLabel: null,
    stock: 35,
    featured: false,
    imageUrl: img("photo-1617137968427-85924c800a22"),
  },
  {
    name: "Pantalón Vestir Hombre",
    description: "Pantalón de vestir en mezcla de lana con corte recto y pinzas. Elegancia para la oficina.",
    category: "Pantalones",
    price: 79.0,
    salePrice: null,
    isOnSale: false,
    saleLabel: null,
    stock: 28,
    featured: false,
    imageUrl: img("photo-1509631179647-0177331693ae"),
  },
  {
    name: "Blazer Mujer Oversize",
    description: "Blazer holgado de estructura suave con hombros caídos y cierre simple. Tendencia oversized.",
    category: "Chaquetas",
    price: 115.0,
    salePrice: 86.0,
    isOnSale: true,
    saleLabel: "Temporada",
    stock: 19,
    featured: false,
    imageUrl: img("photo-1542272604-787c3835535d"),
  },
  // ─── Zapatos de hombre y mujer ────────────────────────────────────────────
  {
    name: "Zapatos Oxford Cuero Negro",
    description: "Oxfords clásicos en cuero genuino con punta cap. Calzado formal de máxima durabilidad.",
    category: "Zapatos",
    price: 129.0,
    salePrice: null,
    isOnSale: false,
    saleLabel: null,
    stock: 20,
    featured: false,
    imageUrl: img("photo-1552422554-0d5af0c79fc6"),
  },
  {
    name: "Zapatos Derby Cuero Marrón",
    description: "Derbys de cuero marrón con costuras visibles y suela de goma. Elegancia con comodidad.",
    category: "Zapatos",
    price: 119.0,
    salePrice: 89.0,
    isOnSale: true,
    saleLabel: "Oferta",
    stock: 17,
    featured: false,
    imageUrl: img("photo-1625357165350-bdbcb6d7d524"),
  },
  {
    name: "Tacones Stiletto Mujer",
    description: "Tacones de aguja de 9 cm con punta cerrada y plataforma oculta. Femeninos y versátiles.",
    category: "Zapatos",
    price: 75.0,
    salePrice: null,
    isOnSale: false,
    saleLabel: null,
    stock: 15,
    featured: false,
    imageUrl: img("photo-1595950653106-6c9ebd614d3a"),
  },
  {
    name: "Sandalias de Tacón Mujer",
    description: "Sandalias de tacón medio con tiras cruzadas y hebilla lateral. Ideal para ocasiones especiales.",
    category: "Zapatos",
    price: 49.0,
    salePrice: null,
    isOnSale: false,
    saleLabel: null,
    stock: 26,
    featured: false,
    imageUrl: img("photo-1543163521-1bf539c55dd2"),
  },
  {
    name: "Sneakers Deportivos Hombre",
    description: "Zapatillas deportivas con amortiguación en espuma y upper transpirable. Máximo confort diario.",
    category: "Zapatos",
    price: 95.0,
    salePrice: 66.0,
    isOnSale: true,
    saleLabel: "Flash sale",
    stock: 33,
    featured: false,
    imageUrl: img("photo-1560343090-f0409e92791a"),
  },
  {
    name: "Botines de Cuero Hombre",
    description: "Botines Chelsea en cuero marrón con elásticos laterales y suela antideslizante. Casual elegante.",
    category: "Zapatos",
    price: 105.0,
    salePrice: null,
    isOnSale: false,
    saleLabel: null,
    stock: 21,
    featured: false,
    imageUrl: img("photo-1531310197839-ccf54634509e"),
  },
  {
    name: "Mocasines Casual Mujer",
    description: "Mocasines en piel suave con hebilla metálica y suela ligera. Comodidad sin sacrificar estilo.",
    category: "Zapatos",
    price: 58.0,
    salePrice: null,
    isOnSale: false,
    saleLabel: null,
    stock: 24,
    featured: false,
    imageUrl: img("photo-1596703263926-eb0762ee17e4"),
  },
  // ─── Teléfonos Samsung y Xiaomi Redmi ─────────────────────────────────────
  {
    name: "Samsung Galaxy S24 Ultra",
    description: "Smartphone flagship con pantalla Dynamic AMOLED 2X de 6.8\", cámara de 200 MP, procesador Snapdragon 8 Gen 3 y batería de 5000 mAh. Almacenamiento 256 GB.",
    category: "Teléfonos",
    price: 1199.0,
    salePrice: 1099.0,
    isOnSale: true,
    saleLabel: "Lanzamiento",
    stock: 8,
    featured: true,
    imageUrl: img("photo-1610945265064-0e34e5519bbf"),
  },
  {
    name: "Samsung Galaxy A55 5G",
    description: "Smartphone gama media premium con pantalla Super AMOLED de 6.6\", cámara triple de 50 MP y batería de 5000 mAh. 128 GB con expansión microSD.",
    category: "Teléfonos",
    price: 399.0,
    salePrice: null,
    isOnSale: false,
    saleLabel: null,
    stock: 15,
    featured: false,
    imageUrl: img("photo-1574944985070-8f3ebc6b79d2"),
  },
  {
    name: "Samsung Galaxy A15",
    description: "Smartphone de entrada con pantalla AMOLED de 6.5\", cámara de 50 MP y batería de 5000 mAh. 128 GB.",
    category: "Teléfonos",
    price: 199.0,
    salePrice: 169.0,
    isOnSale: true,
    saleLabel: "Oferta",
    stock: 20,
    featured: false,
    imageUrl: img("photo-1580910051074-3eb694886505"),
  },
  {
    name: "Xiaomi Redmi Note 13 Pro",
    description: "Smartphone con pantalla AMOLED de 6.67\" a 120Hz, cámara de 200 MP, carga rápida de 67W y 256 GB. Sobresaliente relación calidad-precio.",
    category: "Teléfonos",
    price: 329.0,
    salePrice: 289.0,
    isOnSale: true,
    saleLabel: "Destacado",
    stock: 18,
    featured: true,
    imageUrl: img("photo-1616348436168-de43ad0db179"),
  },
  {
    name: "Xiaomi Redmi 13C",
    description: "Smartphone económico con pantalla de 6.74\", cámara de 50 MP y batería de 5000 mAh. 128 GB.",
    category: "Teléfonos",
    price: 149.0,
    salePrice: null,
    isOnSale: false,
    saleLabel: null,
    stock: 25,
    featured: false,
    imageUrl: img("photo-1580910051074-3eb694886505"),
  },
  {
    name: "Samsung Galaxy Z Flip 6",
    description: "Smartphone plegable compacto con pantalla externa Super AMOLED, cámara de 50 MP y Snapdragon 8 Gen 3. 256 GB.",
    category: "Teléfonos",
    price: 999.0,
    salePrice: null,
    isOnSale: false,
    saleLabel: null,
    stock: 6,
    featured: false,
    imageUrl: img("photo-1511707171634-5f897ff02aa9"),
  },
  // ─── Accesorios para teléfonos (covers y mica) ────────────────────────────
  {
    name: "Funda Transparente Anti-Golpes",
    description: "Funda de silicona transparente con esquinas reforzadas anti-impacto y bisel elevado para proteger la cámara.",
    category: "Accesorios para teléfonos",
    price: 9.0,
    salePrice: null,
    isOnSale: false,
    saleLabel: null,
    stock: 100,
    featured: false,
    imageUrl: img("photo-1535157412991-2ef801c1748b"),
  },
  {
    name: "Funda de Cuero Elegante",
    description: "Funda de piel sintética con acabado liso, cierre magnético y interior forrado para tarjetas.",
    category: "Accesorios para teléfonos",
    price: 19.0,
    salePrice: 14.0,
    isOnSale: true,
    saleLabel: "Oferta",
    stock: 55,
    featured: false,
    imageUrl: img("photo-1620786963525-4a74f1697a46"),
  },
  {
    name: "Funda Rígida Slim Negra",
    description: "Carcasa rígida de policarbonato de perfil delgado con agarre antideslizante. Protección básica discreta.",
    category: "Accesorios para teléfonos",
    price: 7.0,
    salePrice: null,
    isOnSale: false,
    saleLabel: null,
    stock: 80,
    featured: false,
    imageUrl: img("photo-1604671748253-e683240e7efa"),
  },
  {
    name: "Pack Fundas de Colores (x3)",
    description: "Juego de 3 fundas de silicona en colores vibrantes. Venta por paquete para variar tu estilo.",
    category: "Accesorios para teléfonos",
    price: 12.0,
    salePrice: null,
    isOnSale: false,
    saleLabel: null,
    stock: 40,
    featured: false,
    imageUrl: img("photo-1593830566460-2464575a9a24"),
  },
  {
    name: "Mica Templada 9D",
    description: "Protector de vidrio templado 9D con dureza 9H, cobertura completa y revestimiento oleofóbico. Incluye kit de limpieza.",
    category: "Accesorios para teléfonos",
    price: 6.0,
    salePrice: null,
    isOnSale: false,
    saleLabel: null,
    stock: 120,
    featured: false,
    imageUrl: img("photo-1567428486597-8c5328fd3816"),
  },
  {
    name: "Mica de Cristal Transparente",
    description: "Protector de pantalla en cristal templado de alta claridad con auto-reparación de rayones leves.",
    category: "Accesorios para teléfonos",
    price: 5.0,
    salePrice: null,
    isOnSale: false,
    saleLabel: null,
    stock: 95,
    featured: false,
    imageUrl: img("photo-1628866971123-6697eb767771"),
  },
  {
    name: "Cargador Rápido USB-C 25W",
    description: "Adaptador de carga rápida con puerto USB-C y cable incluido. Compatible con Samsung y Xiaomi.",
    category: "Accesorios para teléfonos",
    price: 22.0,
    salePrice: 17.0,
    isOnSale: true,
    saleLabel: "Oferta",
    stock: 48,
    featured: false,
    imageUrl: img("photo-1546054454-aa26e2b734c7"),
  },
  {
    name: "Audífonos Inalámbricos TWS",
    description: "Audífonos Bluetooth con estuche de carga, cancelación de ruido pasiva y 24 horas de batería total.",
    category: "Accesorios para teléfonos",
    price: 35.0,
    salePrice: null,
    isOnSale: false,
    saleLabel: null,
    stock: 30,
    featured: false,
    imageUrl: img("photo-1593476550610-87baa860004a"),
  },
  // ─── Accesorios de maquillaje Mary Kay ────────────────────────────────────
  {
    name: "Set Brochas Esenciales Mary Kay",
    description: "Colección de 5 brochas de fibra sintética para polvo, rubor y ojos, con estuche de viaje. Aplicación profesional.",
    category: "Belleza Mary Kay",
    price: 45.0,
    salePrice: 38.0,
    isOnSale: true,
    saleLabel: "Kit esencial",
    stock: 12,
    featured: false,
    imageUrl: img("photo-1596462502278-27bfdc403348"),
  },
  {
    name: "Labial Líquido Mate Mary Kay",
    description: "Labial líquido de larga duración con acabado mate, fórmula hidratante y alta pigmentación. Tonos intensos.",
    category: "Belleza Mary Kay",
    price: 18.0,
    salePrice: null,
    isOnSale: false,
    saleLabel: null,
    stock: 40,
    featured: false,
    imageUrl: img("photo-1586495777744-4413f21062fa"),
  },
  {
    name: "Paleta de Sombras 12 Tonos",
    description: "Paleta con 12 sombras en acabados mate y shimmer. De diario a smokey eye en un solo producto.",
    category: "Belleza Mary Kay",
    price: 28.0,
    salePrice: 22.0,
    isOnSale: true,
    saleLabel: "Oferta",
    stock: 18,
    featured: false,
    imageUrl: img("photo-1512496015851-a90fb38ba796"),
  },
  {
    name: "Máscara de Pestañas Voluminizadora",
    description: "Rímel que aporta volumen extremo y alarga las pestañas sin grumos. Fórmula a prueba de agua.",
    category: "Belleza Mary Kay",
    price: 16.0,
    salePrice: null,
    isOnSale: false,
    saleLabel: null,
    stock: 35,
    featured: false,
    imageUrl: img("photo-1522335789203-aabd1fc54bc9"),
  },
  {
    name: "Base Líquida de Larga Duración",
    description: "Base de cobertura media a completa con acabado natural y SPF 20. No reseca ni se cuartea.",
    category: "Belleza Mary Kay",
    price: 24.0,
    salePrice: null,
    isOnSale: false,
    saleLabel: null,
    stock: 22,
    featured: false,
    imageUrl: img("photo-1631730359585-38a4935cbec4"),
  },
  {
    name: "Polvo Compacto Traslúcido",
    description: "Polvo suelto fino que fija el maquillaje y controla el brillo. Acabado mate natural.",
    category: "Belleza Mary Kay",
    price: 14.0,
    salePrice: null,
    isOnSale: false,
    saleLabel: null,
    stock: 30,
    featured: false,
    imageUrl: img("photo-1587825140708-dfaf72ae4b04"),
  },
  {
    name: "Kit de Limpieza Facial Mary Kay",
    description: "Juego de limpiador, tónico e hidratante facial en presentación de viaje. Rutina completa de cuidado.",
    category: "Belleza Mary Kay",
    price: 49.0,
    salePrice: 39.0,
    isOnSale: true,
    saleLabel: "Ritual",
    stock: 14,
    featured: false,
    imageUrl: img("photo-1570172619644-dfd03ed5d881"),
  },
  // ─── Aseo personal (cremas y spray corporal) ──────────────────────────────
  {
    name: "Body Spray Mary Kay (Caja x12)",
    description: "Caja de 12 unidades de spray corporal. Venta al por mayor para reventa o regalo.",
    category: "Aseo personal",
    price: 6.0,
    salePrice: null,
    isOnSale: false,
    saleLabel: null,
    stock: 120,
    featured: false,
    imageUrl: img("photo-1587017539504-67cfbddac569"),
    isWholesale: true,
    wholesaleUnitName: "Caja",
    wholesaleUnitQuantity: 12,
  },
  {
    name: "Spray Corporal Floral Fresh",
    description: "Spray corporal de fragancia floral fresca que hidrata y perfuma la piel. Aplicación ligera de larga duración.",
    category: "Aseo personal",
    price: 12.0,
    salePrice: null,
    isOnSale: false,
    saleLabel: null,
    stock: 60,
    featured: false,
    imageUrl: img("photo-1541643600914-78b084683601"),
  },
  {
    name: "Spray Corporal Mango Tropical",
    description: "Spray corporal con aroma tropical de mango y notas dulces. Sensación refrescante para el día.",
    category: "Aseo personal",
    price: 12.0,
    salePrice: 9.0,
    isOnSale: true,
    saleLabel: "Oferta",
    stock: 50,
    featured: false,
    imageUrl: img("photo-1592945403244-b3fbafd7f539"),
  },
  {
    name: "Crema Corporal Hidratante de Mantequilla",
    description: "Crema de cuerpo de mantequilla de karité con 24h de hidratación. Textura rica que se absorbe rápido.",
    category: "Aseo personal",
    price: 15.0,
    salePrice: null,
    isOnSale: false,
    saleLabel: null,
    stock: 45,
    featured: false,
    imageUrl: img("photo-1585232350744-974fc9804d65"),
  },
  {
    name: "Crema Facial de Noche Reparadora",
    description: "Crema de noche con ácido hialurónico y vitamina E. Regenera la piel mientras duermes.",
    category: "Aseo personal",
    price: 26.0,
    salePrice: 20.0,
    isOnSale: true,
    saleLabel: "Skin care",
    stock: 28,
    featured: false,
    imageUrl: img("photo-1623143445418-40c192fa3d11"),
  },
  {
    name: "Loción Corporal Mango & Cocoa",
    description: "Loción hidratante corporal con aroma a mango y cacao. Piel suave y perfumada todo el día.",
    category: "Aseo personal",
    price: 13.0,
    salePrice: null,
    isOnSale: false,
    saleLabel: null,
    stock: 42,
    featured: false,
    imageUrl: img("photo-1498843053639-170ff2122f35"),
  },
  {
    name: "Crema de Manos Reparadora",
    description: "Crema de manos enriquecida con glicerina y aloe vera. Repara manos secas y agrietadas.",
    category: "Aseo personal",
    price: 8.0,
    salePrice: null,
    isOnSale: false,
    saleLabel: null,
    stock: 70,
    featured: false,
    imageUrl: img("photo-1556228720-195a672e8a03"),
  },
  {
    name: "Set Gel & Loción de Ducha",
    description: "Set de gel de baño y loción corporal del mismo aroma. Rutina completa de higiene y frescura.",
    category: "Aseo personal",
    price: 21.0,
    salePrice: 17.0,
    isOnSale: true,
    saleLabel: "Pack",
    stock: 33,
    featured: false,
    imageUrl: img("photo-1556228578-8c89e6adf883"),
  },
  {
    name: "Body Spray Vainilla & Algodón (Caja x12)",
    description: "Caja de 12 unidades de spray corporal con aroma a vainilla y algodón. Ideal para venta al por mayor.",
    category: "Aseo personal",
    price: 6.0,
    salePrice: null,
    isOnSale: false,
    saleLabel: null,
    stock: 100,
    featured: false,
    imageUrl: img("photo-1594035910387-fea47794261f"),
    isWholesale: true,
    wholesaleUnitName: "Caja",
    wholesaleUnitQuantity: 12,
  },
  // ─── Ropa adicional hombre/mujer ──────────────────────────────────────────
  {
    name: "Sudadera Oversize Mujer",
    description: "Sudadera de corte oversize en algodón suave con mangas caídas. Street style cómodo.",
    category: "Sudaderas",
    price: 49.0,
    salePrice: null,
    isOnSale: false,
    saleLabel: null,
    stock: 27,
    featured: false,
    imageUrl: img("photo-1509631179647-0177331693ae"),
  },
  {
    name: "Falda Midi Plisada Mujer",
    description: "Falda midi plisada de cintura elástica con vuelo ligero. Femenina y versátil.",
    category: "Vestidos",
    price: 45.0,
    salePrice: null,
    isOnSale: false,
    saleLabel: null,
    stock: 20,
    featured: false,
    imageUrl: img("photo-1512353087810-25dfcd100962"),
  },
  {
    name: "Camisa Blanca Formal Hombre",
    description: "Camisa blanca de vestir en algodón popelín con cuello italiano. Imprescindible del armario.",
    category: "Camisetas",
    price: 38.0,
    salePrice: null,
    isOnSale: false,
    saleLabel: null,
    stock: 32,
    featured: false,
    imageUrl: img("photo-1487222477894-8943e31ef7b2"),
  },
  {
    name: "Suéter de Cuello Alto Mujer",
    description: "Suéter de cuello alto en tejido de punto grueso. Calidez elegante para el invierno.",
    category: "Sudaderas",
    price: 52.0,
    salePrice: null,
    isOnSale: false,
    saleLabel: null,
    stock: 23,
    featured: false,
    imageUrl: img("photo-1434389677669-e08b4cac3105"),
  },
  {
    name: "Chaleco Bomber Hombre",
    description: "Chaleco acolchado estilo bomber con cremallera y bolsillos exteriores. Casual deportivo.",
    category: "Chaquetas",
    price: 88.0,
    salePrice: null,
    isOnSale: false,
    saleLabel: null,
    stock: 18,
    featured: false,
    imageUrl: img("photo-1525507119028-ed4c629a60a3"),
  },
];

async function main() {
  const adminPassword = process.env.ADMIN_PASSWORD ?? "admin1234";
  await prisma.user.upsert({
    where: { email: "admin@cesarfashion.com" },
    update: {},
    create: {
      email: "admin@cesarfashion.com",
      name: "Cesar Admin",
      role: "admin",
      password: hashPassword(adminPassword),
    },
  });

  const gestorPassword = process.env.GESTOR_PASSWORD ?? "gestor1234";
  await prisma.user.upsert({
    where: { email: "gestor@cesarfashion.com" },
    update: {},
    create: {
      email: "gestor@cesarfashion.com",
      name: "Gestor Tienda",
      role: "gestor",
      password: hashPassword(gestorPassword),
    },
  });

  await prisma.product.deleteMany();
  await prisma.combo.deleteMany();

  const created: { id: string; name: string }[] = [];
  for (const p of PRODUCTS) {
    const { isWholesale, wholesaleUnitName, wholesaleUnitQuantity, ...rest } = p;
    const product = await prisma.product.create({
      data: {
        ...rest,
        currency: "USD",
        isWholesale: isWholesale ?? false,
        wholesaleUnitName: wholesaleUnitName ?? null,
        wholesaleUnitQuantity: wholesaleUnitQuantity ?? 1,
      },
    });
    created.push({ id: product.id, name: product.name });
  }

  const camisa = created.find((p) => p.name.includes("Camisa Oxford"));
  const pantalon = created.find((p) => p.name.includes("Pantalón Chino"));
  if (camisa && pantalon) {
    await prisma.combo.create({
      data: {
        name: "Set Oficina Esencial",
        description: "Camisa Oxford blanca + pantalón chino slim. El dúo perfecto para un look de oficina impecable.",
        price: 115.0,
        salePrice: 99.0,
        currency: "USD",
        isOnSale: true,
        saleLabel: "Pack ahorro",
        featured: true,
        imageUrl: img("photo-1602810318383-e386cc2a3ccf"),
        items: {
          create: [
            { productId: camisa.id, quantity: 1 },
            { productId: pantalon.id, quantity: 1 },
          ],
        },
      },
    });
  }

  const categories = [...new Set(PRODUCTS.map((p) => p.category))];
  console.log(`Seed completado: ${PRODUCTS.length} productos y 1 combo creados.`);
  console.log(`Categorías: ${categories.join(", ")}`);
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(() => prisma.$disconnect());
